# Generated by Django 6.0.6 on 2026-08-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moodle_integration", "0002_moodleuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="LauncherSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("moodle_user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="launcher_sessions", to="moodle_integration.moodleuser")),
            ],
            options={
                "verbose_name": "sesion del launcher",
                "verbose_name_plural": "sesiones del launcher",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["moodle_user", "expires_at"], name="identity_session_user_exp")],
            },
        ),
        migrations.CreateModel(
            name="LauncherAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("launcher_session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="access_tokens", to="identity.launchersession")),
            ],
            options={
                "verbose_name": "token de acceso del launcher",
                "verbose_name_plural": "tokens de acceso del launcher",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["launcher_session", "expires_at"], name="identity_access_sess_exp")],
            },
        ),
        migrations.CreateModel(
            name="LauncherRefreshToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("launcher_session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refresh_tokens", to="identity.launchersession")),
                ("replaced_by", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replaces", to="identity.launcherrefreshtoken")),
            ],
            options={
                "verbose_name": "token de renovacion del launcher",
                "verbose_name_plural": "tokens de renovacion del launcher",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["launcher_session", "expires_at"], name="identity_refresh_sess_exp")],
            },
        ),
        migrations.CreateModel(
            name="ExperienceLaunch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("application_id", models.CharField(max_length=128)),
                ("ticket_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("ticket_expires_at", models.DateTimeField()),
                ("ticket_used_at", models.DateTimeField(blank=True, null=True)),
                ("xapi_token_digest", models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("absolute_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.CharField(blank=True, choices=[("application_closed", "Aplicacion cerrada"), ("replaced", "Reemplazado por otro lanzamiento"), ("logout", "Sesion cerrada"), ("idle_timeout", "Tiempo de inactividad agotado"), ("max_duration", "Duracion maxima agotada")], max_length=32)),
                ("launcher_session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="experience_launches", to="identity.launchersession")),
                ("moodle_user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="experience_launches", to="moodle_integration.moodleuser")),
            ],
            options={
                "verbose_name": "lanzamiento de experiencia",
                "verbose_name_plural": "lanzamientos de experiencias",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["launcher_session", "application_id", "closed_at"], name="identity_launch_sess_app")],
            },
        ),
    ]
