# Generated by Django 6.0.6 on 2026-08-12 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('event_name', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('site_url', models.URLField(max_length=2048)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('resource', models.JSONField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_count', models.PositiveIntegerField(default=1)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('forwarded_for', models.CharField(blank=True, max_length=1024)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('processing_status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='received', max_length=16)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'evento de Moodle',
                'verbose_name_plural': 'eventos de Moodle',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['processing_status', 'received_at'], name='moodle_evt_status_time'), models.Index(fields=['event_name', 'occurred_at'], name='moodle_evt_event_time')],
            },
        ),
    ]
