# Generated by Django 6.0.6 on 2026-08-12 05:13

import django.db.models.deletion
from django.db import migrations, models


USER_FIELD_MAPPING = {
    'username': 'username',
    'idnumber': 'idnumber',
    'firstname': 'first_name',
    'lastname': 'last_name',
    'email': 'email',
}


def backfill_moodle_users(apps, schema_editor):
    MoodleEvent = apps.get_model('moodle_integration', 'MoodleEvent')
    MoodleUser = apps.get_model('moodle_integration', 'MoodleUser')

    events = MoodleEvent.objects.order_by('occurred_at', 'received_at', 'pk')
    for event in events.iterator():
        user_payload = event.resource.get('user')
        if not isinstance(user_payload, dict) or not user_payload.get('id'):
            continue

        deleted_by_event = event.event_name == r'core\event\user_deleted'
        incoming_deleted = user_payload.get('deleted')
        incoming_suspended = user_payload.get('suspended')
        is_deleted = deleted_by_event or bool(incoming_deleted)
        is_suspended = is_deleted or bool(incoming_suspended)
        profile_defaults = {
            target_name: user_payload.get(source_name) or ''
            for source_name, target_name in USER_FIELD_MAPPING.items()
        }

        moodle_user, created = MoodleUser.objects.get_or_create(
            site_url=event.site_url.rstrip('/'),
            moodle_user_id=user_payload['id'],
            defaults={
                **profile_defaults,
                'raw_profile': user_payload,
                'is_suspended': is_suspended,
                'is_deleted': is_deleted,
                'suspended_at': event.occurred_at if is_suspended else None,
                'deleted_at': event.occurred_at if is_deleted else None,
                'last_seen_at': event.occurred_at,
                'last_event': event,
            },
        )
        if created:
            continue

        for source_name, target_name in USER_FIELD_MAPPING.items():
            value = user_payload.get(source_name)
            if value is not None:
                setattr(moodle_user, target_name, value)

        merged_profile = dict(moodle_user.raw_profile)
        merged_profile.update(
            {
                key: value
                for key, value in user_payload.items()
                if value is not None
            }
        )
        moodle_user.raw_profile = merged_profile

        if incoming_suspended is not None:
            moodle_user.is_suspended = bool(incoming_suspended)
            moodle_user.suspended_at = (
                event.occurred_at if incoming_suspended else None
            )

        if is_deleted:
            moodle_user.is_deleted = True
            moodle_user.deleted_at = moodle_user.deleted_at or event.occurred_at
            moodle_user.is_suspended = True
            moodle_user.suspended_at = (
                moodle_user.suspended_at or event.occurred_at
            )
        elif moodle_user.is_deleted:
            moodle_user.is_suspended = True
            moodle_user.suspended_at = (
                moodle_user.suspended_at or event.occurred_at
            )

        moodle_user.last_seen_at = event.occurred_at
        moodle_user.last_event = event
        moodle_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('moodle_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(max_length=2048)),
                ('moodle_user_id', models.PositiveBigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('idnumber', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('raw_profile', models.JSONField(default=dict)),
                ('is_suspended', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('last_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='synchronized_users', to='moodle_integration.moodleevent')),
            ],
            options={
                'verbose_name': 'usuario de Moodle',
                'verbose_name_plural': 'usuarios de Moodle',
                'ordering': ('site_url', 'moodle_user_id'),
                'indexes': [models.Index(fields=['site_url', 'is_suspended'], name='moodle_user_status_idx'), models.Index(fields=['site_url', 'last_seen_at'], name='moodle_user_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_url', 'moodle_user_id'), name='moodle_user_site_id_uniq'), models.CheckConstraint(condition=models.Q(('is_deleted', False), ('is_suspended', True), _connector='OR'), name='moodle_user_deleted_suspended')],
            },
        ),
        migrations.RunPython(backfill_moodle_users, migrations.RunPython.noop),
    ]
